---
changelog:
  - changes:
    - text: "Message reducer deduplication logic updated to replace old message if timetokens match"
      type: enhancement
    date: 2020-04-16
    version: v0.1.2
  - changes:
    - text: "Membership/Member actions now include the removed/left elements"
      type: enhancement
    date: 2020-03-30
    version: v0.1.1
  - changes:
    - text: "Initial release of PubNubCSM"
      type: feature
    date: 2020-03-30
    version: v0.1.0
supported-platforms:
  - platforms:
      - iOS 8.0 or higher
      - macOS 10.10 or higher
      - tvOS 9.0 or higher
      - watchOS 2.0 or higher
name: swift-pubnubcsm
scm: github.com/pubnub/swift-pubnubcsm
version: "1.0.0"
schema: 1
